name: Copy file to/from S3
description: Installs AWS CLI and copies files between local and S3-compatible storage

inputs:
  aws_access_key_id:
    description: AWS access key ID
    required: true
  aws_secret_access_key:
    description: AWS secret access key
    required: true
  aws_endpoint_url:
    description: AWS endpoint URL
    required: true
  source:
    description: Source path(s). Supports multiline strings for multiple files.
    required: true
  destination:
    description: Destination path (can be local or s3://...)
    required: true
  recursive:
    description: Copy files recursively
    default: 'false'
  quiet:
    description: Suppress output
    default: 'false'
  region:
    description: AWS region
    required: false
    default: 'us-east-1'
  no_verify_ssl:
    description: Disable SSL verification
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Debug Files
      shell: bash
      run: |
        echo "=== listing current directory ==="
        ls -la
        echo "=== checking if plan.tfplan is a file or dir ==="
        ls -ld plan.tfplan

    - name: Copy file(s)
      shell: bash
      env:
        AWS_ACCESS_KEY_ID: ${{ inputs.aws_access_key_id }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.aws_secret_access_key }}
        AWS_ENDPOINT_URL: ${{ inputs.aws_endpoint_url }}
        AWS_REGION: ${{ inputs.region }}
        SOURCES: ${{ inputs.source }}
      run: |
        FLAGS=""
        [[ "${{ inputs.recursive }}" == "true" ]] && FLAGS+=" --recursive"
        [[ "${{ inputs.quiet }}" == "true" ]] && FLAGS+=" --quiet"
        [[ "${{ inputs.no_verify_ssl }}" == "true" ]] && FLAGS+=" --no-verify-ssl"

        echo "$SOURCES" | while IFS= read -r src; do
          [ -z "$src" ] && continue
          aws s3 cp "$src" "${{ inputs.destination }}" $FLAGS
        done
