name: Remove file(s) from S3
description: Installs AWS CLI and deletes file(s) from an S3-compatible bucket

inputs:
  aws_access_key_id:
    description: AWS access key ID
    required: true
  aws_secret_access_key:
    description: AWS secret access key
    required: true
  aws_endpoint_url:
    description: AWS endpoint URL (e.g., https://s3.amazonaws.com or https://minio.example.com)
    required: true
  bucket:
    description: Name of the S3 bucket
    required: true
  remote_path:
    description: Path to the file or directory in the S3 bucket (e.g., path/to/file.txt or path/to/directory/)
    required: true
  recursive:
    description: Remove files recursively (if the remote path is a directory)
    default: 'false'
  quiet:
    description: Suppress output
    default: 'false'
  region:
    description: AWS region (e.g., us-east-1)
    required: false
  no_verify_ssl:
    description: Disable SSL verification
    default: 'true'

runs:
  using: "composite"
  steps:
    - name: Install AWS CLI
      uses: unfor19/install-aws-cli-action@v1
      with:
        arch: ${{ runner.arch }}

    - name: Delete file from S3
      shell: bash
      env:
        AWS_ACCESS_KEY_ID: ${{ inputs.aws_access_key_id }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.aws_secret_access_key }}
        AWS_ENDPOINT_URL: ${{ inputs.aws_endpoint_url }}
        AWS_REGION: ${{ inputs.region }}
      run: |
        FLAGS=""
        [[ "${{ inputs.recursive }}" == "true" ]] && FLAGS+=" --recursive"
        [[ "${{ inputs.quiet }}" == "true" ]] && FLAGS+=" --quiet"
        [[ "${{ inputs.no_verify_ssl }}" == "true" ]] && FLAGS+=" --no-verify-ssl"
        aws s3 rm s3://${{ inputs.bucket }}/${{ inputs.remote_path }} $FLAGS
